name=MKE_I2C_AHT20
version=1.0.0
author=MakerEdu.vn
maintainer=MakerEdu.vn
sentence=Library for MKE I2C AHT20 temperature and humidity sensor
paragraph=Provides an easy interface to control the MKE-M26-AHT20-I2C-MODULE.
category=Sensors
url=https://github.com/makereduvn
architectures=*
includes=MKE_I2C_AHT20.h
